# pedir_productos_worker:
#   cron: "*/11 * * * *"
#   class: PedirFinalesWorker
#   queue: ordenes

control_de_inventario:
  cron: "17 * * * *"
  class: InventoryWorker
  queue: default

# review_worker:
#   cron: "*/3 * * * *"
#   class: ReviewWorker
#   queue: default

# arrocero:
#   cron: "*/10 * * * *"
#   class: HacerArrozWorker
#   queue: default

control_materias_primas:
  cron: "15,45 * * * *"
  class: MateriaPrimaWorker
  queue: default

despachadar_ftps:
  cron: "*/2 * * * *"
  class: DespacharWorker
  queue: default