# pedir_productos_worker:
#   cron: "*/11 * * * *"
#   class: PedirFinalesWorker
#   queue: ordenes

control_de_inventario:
  cron: "*/10 * * * *"
  class: InventoryWorker
  queue: default

review_worker:
  cron: "*/2 * * * *"
  class: ReviewWorker
  queue: despacho

arrocero_worker:
  cron: "*/5 * * * *"
  class: ArroceroWorker
  queue: default

control_materias_primas:
  cron: "*/15 * * * *"
  class: MateriaPrimaWorker
  queue: default

despachadar_ftps:
  cron: "*/3 * * * *"
  class: DespacharWorker
  queue: despacho

