pedir_productos_worker:
  cron: "19 * * * *"
  class: PedirFinalesWorker
  queue: ordenes

# control_de_inventario:
#   cron: "34 * * * *"
#   class: InventoryWorker
#   queue: default

# review_worker:
#   cron: "*/10 * * * *"
#   class: ReviewWorker
#   queue: default
