pedir_productos_worker:
  cron: "*/11 * * * *"
  class: PedirFinalesWorker
  queue: ordenes

control_de_inventario:
  cron: "*/30 * * * *"
  class: InventoryWorker
  queue: default

review_worker:
  cron: "*/3 * * * *"
  class: ReviewWorker
  queue: default
