# pedir_productos_worker:
#   cron: "*/11 * * * *"
#   class: PedirFinalesWorker
#   queue: ordenes

# control_de_inventario:
#   cron: "*/30 * * * *"
#   class: InventoryWorker
#   queue: default

# review_worker:
#   cron: "*/2 * * * *"
#   class: ReviewWorker
#   queue: despacho

arrocero_worker:
  cron: "32 * * * *"
  class: ArroceroWorker
  queue: default

# control_materias_primas:
#   cron: "15,45 * * * *"
#   class: MateriaPrimaWorker
#   queue: default

# despachadar_ftps:
#   cron: "*/3 * * * *"
#   class: DespacharWorker
#   queue: despacho